version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lab3_products
    volumes:
      - ./src/app/database:/app/data-out
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: lab3_products
      PGPASSWORD: secret
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src/app/database:/app/data-out
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pgdata:
